In [24]:
import torch
import pandas as pd
df_features_label = pd.read_csv('df_train_set_features_label_time_series.csv', index_col=0)
# a = df_features_label.astype('double')
data = torch.tensor(df_features_label.values, dtype=torch.double)
# data
df_features_label.shape
# a.dtypes

(86, 1501)

In [32]:
data.dtype
data = data.to(dtype=torch.float32)
data

tensor([[1.0271, 1.0274, 1.0269,  ..., 0.5408, 0.5397, 4.0000],
        [0.1658, 0.1583, 0.1618,  ..., 0.1984, 0.2054, 2.0000],
        [0.1861, 0.1987, 0.1968,  ..., 0.1909, 0.1980, 2.0000],
        ...,
        [1.0381, 1.0414, 1.0378,  ..., 1.0335, 1.0353, 6.0000],
        [0.2397, 0.2392, 0.2390,  ..., 0.4830, 0.4873, 3.0000],
        [1.0343, 1.0366, 1.0356,  ..., 1.0339, 1.0351, 6.0000]])

In [27]:
ten = torch.zeros(df_features_label.shape)
ten.dtype
for i,

torch.float32

In [28]:
x = torch.empty(5, 3)
x.dtype

torch.float32

In [3]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()

forest_reg.fit(housing_prepared, housing_labels)
housing_predictions = forest_reg.predict(housing_prepared)
forest_mse = mean_squared_error(housing_predictions, housing_labels)
forest_rmse = np.sqrt(forest_mse)
print("rmse on whole training set")
print(forest_rmse)
print(forest_reg.feature_importances_)

forest_scores = cross_val_score(forest_reg, housing_prepared, housing_labels, 
                               scoring="neg_mean_squared_error", cv=10)
forest_rmse = np.sqrt(-forest_scores)
print("rmse of cross validation")
display_scores(forest_rmse)
print(forest_reg.feature_importances_)

/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


NameError: name 'housing_prepared' is not defined

In [2]:
import numpy as np
a = np.array([2.15295647e+01, 8.12531501e+00, 3.97113829e+00, 1.00777250e+01])
print([ "{:0.2f}".format(x) for x in a ])

['21.53', '8.13', '3.97', '10.08']


In [16]:
import requests

x = requests.get('https://w3schools.com/python/demopage.htm', timeout=6)

print(x.text)

ConnectTimeout: HTTPSConnectionPool(host='w3schools.com', port=443): Max retries exceeded with url: /python/demopage.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f37254ac860>, 'Connection to w3schools.com timed out. (connect timeout=6)'))

In [15]:
import requests

url = 'https://www.w3schools.com/python/demopage.htm'
x = requests.get(url, proxies={'http': 'http://localhost:7890'}, timeout=6)

print(x.text)

<!DOCTYPE html>
<html>
<body>

<h1>This is a Test Page</h1>

</body>
</html>


In [19]:
import requests
url = 'https://www.python.org/static/img/python-logo@2x.png'
# myfile = requests.get(url, timeout=6, proxies={'http': 'http://localhost:7890'})
myfile = requests.get(url, timeout=6, proxies={'http': 'http://localhost:7890'})
open('test.png', 'wb').write(myfile.content)

15770

In [29]:
import requests
# url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz'
# url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz'
url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/'
# myfile = requests.get(url, proxies={'http': 'http://localhost:7890'})
myfile = requests.get(url)
open('housing.tgz', 'wb').write(myfile.content)

ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ageron/handson-ml/master/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f37253a7eb8>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [26]:
import requests

url = 'https://w3schools.com/images/pulpit.jpg'

#allow the response to be streamed by setting the 'stream' parameter to True:
x = requests.get(url, stream=False, proxies={'http': 'http://localhost:7890'})

print(x.status_code)

200


In [58]:
import requests
url = 'https://raw.githubusercontent.com/django/django/master/setup.py'
myfile = requests.get(url, proxies={'http': 'http://localhost:7890'}, timeout=10, verify=False)
# open('test.txt', 'wb').write(myfile.content)

ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /django/django/master/setup.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3724d9e550>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [63]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [65]:
from six.moves import urllib
# url = 'https://raw.githubusercontent.com/django/django/master/setup.py'
url = 'https://github.com/django/django/master/setup.py'
urllib.request.ProxyHandler(proxies={'http': 'http://localhost:7890'})
urllib.request.urlretrieve(url, 'test.py')

HTTPError: HTTP Error 404: Not Found

In [44]:
import urllib3
import urllib
urllib?

In [102]:
import os
import tarfile
from six.moves import urllib

DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def fetch_housing_data(housing_url=HOUSING_URL, housing_path=HOUSING_PATH):
    os.makedirs(housing_path, exist_ok=True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    proxy = urllib.request.ProxyHandler({'https': 'localhost:7890'})
    opener = urllib.request.build_opener(proxy)
    urllib.request.install_opener(opener)
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)
    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()
    
    
fetch_housing_data()

In [69]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [78]:
from six.moves import urllib
url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/README.md'
req = urllib.request.Request(url)
req.set_proxy('localhost:7890', 'http')
urllib.request.urlopen(req)

HTTPError: HTTP Error 404: Not Found

In [97]:
from six.moves import urllib
url = 'https://github.com/ageron/handson-ml'
req = urllib.request.Request(url)
req.set_proxy('localhost:7890', 'http')
response = urllib.request.urlopen(req)
print(response.read().decode('utf8'))







<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" media="all" integrity="sha512-FG+rXqMOivrAjdEQE7tO4BwM1poGmg70hJFTlNSxjX87grtrZ6UnPR8NkzwUHlQEGviu9XuRYeO8zH9YwvZhdg==" rel="stylesheet" href="https://github.githubassets.com/assets/frameworks-146fab5ea30e8afac08dd11013bb4ee0.css" />
  <link crossorigin="anonymous" media="all" integrity="sha512-/AdLBCA+eCrgc3fiUb5+p+bFyPCLqrw0KzL3ZgmaGavn2qE0LVSbYhHMxjTRaATkscS7ertVyGYNyRiT

In [103]:
import requests
url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/README.md'
myfile = requests.get(url, proxies={'https': 'localhost:7890'})
open('test.txt', 'wb').write(myfile.content)

3680

In [116]:
import requests
url = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz'
myfile = requests.get(url, proxies={'https': 'localhost:7890'})
print(type(myfile))
# open('test.tgz', 'wb').write(myfile.content)

<class 'requests.models.Response'>


In [109]:
import tarfile
housing_tgz = tarfile.open('test.tgz')
housing_tgz.extractall()
housing_tgz.close()

# sklearn.linear_model.LinearRegression

In [18]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
print(X)
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([[1], [2]])) + 3
print(y)
reg = LinearRegression().fit(X, y)
print(reg.coef_)
print(reg.intercept_)

print(reg.predict(np.array([[3, 5]])))

[[1 1]
 [1 2]
 [2 2]
 [2 3]]
[[ 6]
 [ 8]
 [ 9]
 [11]]


In [19]:
reg.coef_

array([[1., 2.]])

In [20]:
reg.intercept_

array([3.])

In [22]:
reg.predict(np.array([[3, 5]]))

array([[16.]])

# sklearn.impute.SimpleImputer

In [23]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print(imp_mean.transform(X))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]


In [24]:
imp_mean.statistics_

array([7. , 3.5, 6. ])

In [25]:
imp_mean.indicator_

In [1]:
from sklearn.impute import SimpleImputer